### ISSUE TITLE
A_LookEX Acquires Target Outside of FOV

### ISSUE THREAD

**Issue by silentzorah** [UZDoom/UZDoom#796]
### UZDoom Version

UZDoom 4.14.3

### Game

All

### Operating System

Windows 11

### Duplicate Confirmation

- [x] I have searched and not found a similar issue.

### Bug Description

A_LookEX still acquires a target outside its FOV, as if +LookAllAround is used.  This appears to have been broken in GZDoom 4.10 and hasn't been fixed correctly.  Please see the attached demo, where each beam from a BFG projectile all fire at the same target, whether the target is inside the declared FOV or not (60 degrees is used for the demo).

### Replication

[bfg10kTest.zip](https://github.com/user-attachments/files/24274105/bfg10kTest.zip)

Using the BFG, fire into an area with multiple monsters.  Observed behavior shows six beams all targeting the same monster.  Correct behavior is to only fire arcs at targets found within their FOV of 60 degrees, spawning multiple arcs in different directions instead of all six arcs firing at one.

### Configuration

```ini

```

**Comment by HexaDoken** [comment]
This also happens if LookForEnemies is called directly, and still occurs in UZDoom trunk.

EDIT: LookForEnemiesEx is also affected by this issue.

**Comment by Boondorl** [comment]
Can you test to make sure this is fixed in 5.0? It might've slipped through the cracks in the 4.14.3 release since there was a ton of commits to sift through

**Comment by HexaDoken** [comment]
No, it's still broken the exact same way in 5.0 autobuilds.

**Comment by LuciferSam8086** [comment]
Any news on this issue? Thanks!

**Comment by Xterra1** [comment]
This is still a problem in the latest available build on the DRDTeam website.
